<<<<<<< HEAD
name: Deploy to AWS
=======
name: AWS Test
>>>>>>> 31262dde2bafe05558cffbfeaeb41b8d53a683da

on:
  push:
    branches: [ "main" ]

jobs:
<<<<<<< HEAD
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # REQUIRED for OIDC
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: YOUR_ROLE_ARN
        aws-region: us-east-1

    - name: Verify AWS Access
      run: aws sts get-caller-identity

   
=======
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::476885575020:role/github-acess
        aws-region: us-east-1

    - name: Test
      run: aws sts get-caller-identit
>>>>>>> 31262dde2bafe05558cffbfeaeb41b8d53a683da
